mkrandom/main/urls.py
from django.urls import path, include
from .views import home_page, list_compo, another_one
app_name = 'main'
urlpatterns = [
    path('homepage/',list_compo,name='home'),
    path('anotherone/',another_one,name='another_one')
]

mkrandom/mkrandom/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('main/',include('main.urls')),
]

mkrandom/main/models.py
from django.db import models

# Create your models here.
class Character(models.Model):
    name=models.CharField(max_length=100,blank=True, null=True)
    image_url=models.CharField(max_length=1000,blank=True, null=True)
    index=models.IntegerField(blank=True, null=True)

    def __str__(self):
        return f"{self.name}"
class Vehicle(models.Model):
    name=models.CharField(max_length=100,blank=True, null=True)
    image_url=models.CharField(max_length=1000,blank=True, null=True)
    index=models.IntegerField(blank=True, null=True)

    def __str__(self):
        return f"{self.name}"
class Tire(models.Model):
    name=models.CharField(max_length=100,blank=True, null=True)
    image_url=models.CharField(max_length=1000,blank=True, null=True)
    index=models.IntegerField(blank=True, null=True)

    def __str__(self):
        return f"{self.name}"
class Glider(models.Model):
    name=models.CharField(max_length=100,blank=True, null=True)
    image_url=models.CharField(max_length=1000,blank=True, null=True)
    index=models.IntegerField(blank=True, null=True)

    def __str__(self):
        return f"{self.name}"
class Compo(models.Model):
    char = models.ForeignKey(Character, on_delete=models.CASCADE,blank=True, null=True)
    veh = models.ForeignKey(Vehicle, on_delete=models.CASCADE,blank=True, null=True)
    tire = models.ForeignKey(Tire, on_delete=models.CASCADE,blank=True, null=True)
    glider = models.ForeignKey(Glider, on_delete=models.CASCADE,blank=True, null=True)
    index=models.IntegerField(blank=True, null=True)

    def __str__(self):
        return f"{self.char.name}-{self.veh.name}-{self.tire.name}-{self.glider.name}"

mkrandom/main/views.py
from django.shortcuts import render
from django.views.generic import TemplateView, ListView, DetailView, View
from .models import Character, Vehicle, Tire, Glider, Compo
import random
# Create your views here.

class home_page(TemplateView):
    template_name = "home_page.html"

def list_compo(request):
    choices1 = ['(Orange)','(Rose)','(Blue)','(White)','(Yellow)','(Rose)','(Black)','(Cyan)',]
    choices2 = ['(B)','(G)']
    char_num = random.randint(1,41)
    vehicle_num = random.randint(1,41)
    tire_num = random.randint(1,22)
    glider_num = random.randint(1,15)
    char = Character.objects.get(index=char_num)
    if "Yoshi" in char.name:
        x = random.randint(0,7)
        charname = char.name + f" {choices1[x]}"
        print(charname)
        char = Character.objects.get(name = charname)
        print(f"Got a {char.name}")
    elif "Shyguy" in char.name:
        x = random.randint(0,7)
        charname = char.name + f" {choices1[x]}"
        print(charname)
        char = Character.objects.get(name = charname)
        print(f"Got a {char.name}")
    elif "Inkling" in char.name:
        x = random.randint(0,1)
        charname = char.name[0:7] + f" {choices2[x]}"
        print(charname)
        char = Character.objects.get(name = charname)
        print(f"Got a {char.name}")
    elif "Villager" in char.name:
        x = random.randint(0,1)
        charname = char.name[0:8] + f" {choices2[x]}"
        print(charname)
        char = Character.objects.get(name = charname)
        print(f"Got a {char.name}")
    vehicle = Vehicle.objects.get(index=vehicle_num)
    tire = Tire.objects.get(index=tire_num)
    glider = Glider.objects.get(index=glider_num)

    compo = Compo.objects.get_or_create(char=char, veh=vehicle, tire=tire, glider=glider)[0]
    context = {'compo':compo}
    return render(request,'home_page.html',context)

def another_one(request):
    choices1 = ['(Orange)','(Rose)','(Blue)','(White)','(Yellow)','(Rose)','(Black)','(Cyan)',]
    choices2 = ['(B)','(G)']
    char_num = random.randint(1,41)
    vehicle_num = random.randint(1,41)
    tire_num = random.randint(1,22)
    glider_num = random.randint(1,15)
    char = Character.objects.get(index=char_num)
    if "Yoshi" in char.name:
        x = random.randint(0,7)
        charname = char.name + f" {choices1[x]}"
        print(charname)
        char = Character.objects.get(name = charname)
        print(f"Got a {char.name}")
    elif "Shyguy" in char.name:
        x = random.randint(0,7)
        charname = char.name + f" {choices1[x]}"
        print(charname)
        char = Character.objects.get(name = charname)
        print(f"Got a {char.name}")
    elif "Inkling" in char.name:
        x = random.randint(0,1)
        charname = char.name[0:7] + f" {choices2[x]}"
        print(charname)
        char = Character.objects.get(name = charname)
        print(f"Got a {char.name}")
    elif "Villager" in char.name:
        x = random.randint(0,1)
        charname = char.name[0:8] + f" {choices2[x]}"
        print(charname)
        char = Character.objects.get(name = charname)
        print(f"Got a {char.name}")
    vehicle = Vehicle.objects.get(index=vehicle_num)
    tire = Tire.objects.get(index=tire_num)
    glider = Glider.objects.get(index=glider_num)

    compo = Compo.objects.get_or_create(char=char, veh=vehicle, tire=tire, glider=glider)[0]
    context = {'compo':compo}
    return render(request,'another_one.html',context)

mkrandom/templates/another_one.html
{%load static%}
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/css/bootstrap.min.css" integrity="sha384-B0vP5xmATw1+K9KRQjQERJvTumQW0nPEzvF6L/Z6nronJ3oUOFUFpCjEUQouq2+l" crossorigin="anonymous">
    <meta charset="utf-8">
    <title></title>
    <link rel="stylesheet" href="{%static 'css/homestyle.css'%}">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Press+Start+2P&display=swap" rel="stylesheet">
  </head>
  <body>
    <div class="containercss">
      <div class='box'>
    	  <div class='content'>
          <span class="homebutton">
          <a class="home" href="{%url 'main:home'%}"><img src="https://www.pngkey.com/png/full/8-88353_mario-bros-castle-png.png" alt=""></a>
          </span>
          <div class="secondrandomizer">
            <div class="container-lg">
              <h4 class="text big subtitle">And today's pick will be...</h4>
              <br>
              <div class="lakitu">
                <img class="lakitu_img" src="https://upload.wikimedia.org/wikipedia/en/2/2d/Lakitu.png" alt="">
              </div>

              <br>
              <br>
              <br>
              <br>
              <div class="box-random b">
                <div class="container-lg white b">
                  <div class="row justify-content-around">
                    <div class="col rightborder">
                      <div class="car b">
                        <img src="{{compo.veh.image_url}}" alt="">
                        <br>
                        <br>
                        <br>
                        <p class="text legend">{{compo.veh.name}}</p>
                      </div>
                    </div>

                    <div class="col leftborder rightborder">
                      <div class="character b">
                        <img src="{{compo.char.image_url}}" alt="">
                        <br>
                        <br>
                        <p class="text legend">{{compo.char.name}}</p>
                      </div>
                    </div>
                    <div class="col leftborder rightborder">
                      <div class="tire b">
                        <img src="{{compo.tire.image_url}}" alt="">
                        <br>
                        <br>
                        <br>
                        <p class="text legend">{{compo.tire.name}}</p>
                      </div>
                    </div>

                    <div class="col leftborder">
                      <div class="glider b">
                        <img src="{{compo.glider.image_url}}" alt="">
                        <br>
                        <br>
                        <br>
                        <p class="text legend">{{compo.glider.name}}</p>
                      </div>
                    </div>
                  </div>
                  <div class="reload">
                    <a href="{%url 'main:another_one'%}"><img src="http://pixelartmaker-data-78746291193.nyc3.digitaloceanspaces.com/image/55f3dd1cb4e139f.png" alt=""></a>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </body>
</html>

mkrandom/templates/home_page.html
{%load static%}
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/css/bootstrap.min.css" integrity="sha384-B0vP5xmATw1+K9KRQjQERJvTumQW0nPEzvF6L/Z6nronJ3oUOFUFpCjEUQouq2+l" crossorigin="anonymous">
    <meta charset="utf-8">
    <title></title>
    <link rel="stylesheet" href="{%static 'css/homestyle.css'%}">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Press+Start+2P&display=swap" rel="stylesheet">
  </head>
  <body>
    <div class="containercss">
      <div class='box'>
    	  <div class='content'>
          <span class="homebutton">
          <a class="home" href="{%url 'main:home'%}"><img src="https://www.pngkey.com/png/full/8-88353_mario-bros-castle-png.png" alt=""></a>
          </span>


          <input class="checkbox playbox" type="checkbox" id="toggle">

          <h1 class="text big title">Welcome to the <br> Mario Kart randomizer!</h1>


          <div class="mario">
            <img class="mario_img" src="https://res.cloudinary.com/jerrick/image/upload/v1539195245/ih9lbxdvls4nh42zvetx.png" alt="">
          </div>


          <div class="play">
            <label for="toggle"><img src="https://art.pixilart.com/a9b70c683c2aed9.png" alt=""></label>
          </div>
          <div class="randomizer">
            <div class="container-lg">
              <h4 class="text big subtitle">And today's pick will be...</h4>
              <br>
              <div class="lakitu">
                <img class="lakitu_img" src="https://upload.wikimedia.org/wikipedia/en/2/2d/Lakitu.png" alt="">
              </div>

              <br>
              <br>
              <br>
              <br>

              <div class="box-random b">
                <div class="container white b">
                  <div class="row justify-content-around">
                    <div class="col rightborder">
                      <div class="car b">
                        <img src="{{compo.veh.image_url}}" alt="">
                        <br>
                        <br>
                        <br>
                        <p class="text legend">{{compo.veh.name}}</p>
                      </div>
                    </div>

                    <div class="col leftborder rightborder">
                      <div class="character b">
                        <img src="{{compo.char.image_url}}" alt="">
                        <br>
                        <br>
                        <p class="text legend">{{compo.char.name}}</p>
                      </div>
                    </div>
                    <div class="col leftborder rightborder">
                      <div class="tire b">
                        <img src="{{compo.tire.image_url}}" alt="">
                        <br>
                        <br>
                        <br>

                        <p class="text legend">{{compo.tire.name}}</p>
                      </div>
                    </div>

                    <div class="col leftborder">
                      <div class="glider b">
                        <img src="{{compo.glider.image_url}}" alt="">
                        <br>
                        <br>
                        <br>
                        <p class="text legend">{{compo.glider.name}}</p>
                      </div>
                    </div>
                  </div>
                  <div class="reload">
                    <a href="{%url 'main:another_one'%}"><img src="http://pixelartmaker-data-78746291193.nyc3.digitaloceanspaces.com/image/55f3dd1cb4e139f.png" alt=""></a>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </body>
</html>